---
title: "Authors"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(stringr)
knitr::opts_chunk$set(echo = FALSE)
booklist <- read.csv("booklist.csv") %>%
  mutate(across(ends_with('title'),str_squish))

```

I've also been tracking a little bit about who writes the books I'm reading. Ideally, the books I read will not only entertain me, but expand my worldview. There are lots of ways to think and measure that, but a simple one is to track the
backgrounds of the authors, so I'm starting there.


```{r author-background, message = F, out.width='100%'}

library(plotly)
library(tidyverse)

authors <- booklist %>%
  group_by(year) %>%
  summarise(n = n(),
            pct_of_color = round(100*mean(author.of.color, na.rm = T),1),
            pct_female = round(100*mean(author.female, na.rm = T),1)) 


author_fig <- plot_ly(
  authors, 
  x = ~year, 
  y = ~pct_of_color, 
  name = 'Authors of Color', 
  type = 'scatter', 
  mode = 'lines+markers',
  line = list(color = "#ef5675", width = 4),
  marker = list(color = "#ef5675", size = 6)
) %>%
  add_trace(
    y = ~pct_female, 
    name = 'Female Authors', 
    type = 'scatter', 
    mode = 'lines+markers',
    line = list(color = "#7a5195", width = 4),
    marker = list(color = "#7a5195", size = 6)
  ) %>%
  layout(
    legend = list(orientation = 'h', font = list(size = 12, family = "Arial")),
    yaxis = list(title = 'Percentage', titlefont = list(size = 14, family = "Arial")),
    xaxis = list(title = '', tickfont = list(size = 12, family = "Arial"))
  )

config(author_fig, displayModeBar = FALSE)

  
```
