---
title: "Reading Progress"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(stringr)

booklist <- read.csv("booklist.csv") %>%
  mutate(across(ends_with('title'),str_squish))

```

The goal is to read 24 books (just two a month!) each year, and to include something from the Pulitzer list. Historically this has been impossible for me, and this is an over-engineered exploration of that.

### How I'm doing

There was early progress, and then a decline, and I'm working my way back. It's a journey.

```{r over-time, echo=FALSE, warning=FALSE, message=FALSE, out.width='100%'}
library(plotly)

by_year <- booklist %>%
  rename(Year = year) %>%
  group_by(Year) %>%
  summarise(Books = n())

fig <- plot_ly(by_year, x = ~Year, y = ~Books,
        type = 'scatter', mode = 'lines+markers',fill = 'tozeroy') %>%
  layout(shapes=list(list(type = 'line', 
                                        x0 = 2017,
                                        x1 = 2025, 
                                        y0 = 24,
                                        y1 = 24, 
                                        line = list(width = 2, dash = "dot"))),
         yaxis = list(showline = FALSE,
                      showticklabels = TRUE,
                      tickcolor = 'rgb(127,127,127)',
                      ticks = 'outside',
                      zeroline = FALSE,
                      range = list(0,32),
                      dtick = 4,
                      zerolinewidth = 2),
         xaxis = list(showline = TRUE,
                      zerolinewidth = 6))
config(fig, responsive = T, displayModeBar = F)



```

### What have I read this year?

```{r current-books, echo=FALSE}
library(reactable)

this_year <- max(booklist$year)

current_year <- booklist %>%
  filter(year == this_year) %>%
  select(Order = read.order,
         Title = long.title,
         Author = author) %>%
  arrange(desc(Order))

reactable(current_year,
            columns = list(
    Order = colDef(maxWidth = 75),
    Author = colDef(maxWidth = 300)
  ),
          showSortable = TRUE)

```
